fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

yuande_user_user:
    resource: "@YuandeUserUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
